const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGN_START:'GOOGLE_SIGN_START',
    GOOGLE_SIGN_SUCCESS:'GOOGLE_SIGN_SUCCESS',
    GOOGLE_SIGN_FAILURE:'GOOGLE_SIGN_FAILURE',
    EMAIL_SIGN_START:'EMAIL_SIGN_START',
    EMAIL_SIGN_SUCCESS:'EMAIL_SIGN_SUCCESS',
    EMAIL_SIGN_FAILURE:'EMAIL_SIGN_FAILURE',
}

export default userActionTypes;