const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGN_START:'GOOGLE_SIGN_START',
    EMAIL_SIGN_START:'EMAIL_SIGN_START',
    EMAIL_SIGN_SUCCESS:'SIGN_IN_SUCCESS',
    EMAIL_SIGN_FAILURE:'SIGN_IN_FAILURE',
}

export default userActionTypes;